apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpregisteret
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tpregisteret.nais.preprod.local
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle/creds
        kvPath: oracle/data/dev/creds/tjenestepensjon_q1-user
      - mountPath: /secrets/oracle/config
        kvPath: oracle/data/dev/config/tjenestepensjon_q1
  webproxy: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
  prometheus:
    enabled: true
    path: actuator/prometheus
