CREATE SCHEMA IF NOT EXISTS TJPEN;

CREATE TABLE IF NOT EXISTS TJPEN.T_PERSON(
  PERSON_ID INTEGER,
  FNR_FK VARCHAR (11)
 );

CREATE TABLE IF NOT EXISTS TJPEN.T_FORHOLD(
  FORHOLD_ID INTEGER,
  PERSON_ID INTEGER,
  TSS_EKSTERN_ID_FK VARCHAR (25),
  ER_GYLDIG CHAR (1)
);

CREATE TABLE IF NOT EXISTS TJPEN.T_TSS_TP(
  TSS_ID VARCHAR (20),
  TP_ID VARCHAR (20)
);