name: Release to GitHub Package Registry

on:
  push:
    branches: master

jobs:
  build_release_deploy:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'

      # Build
      - name: Build
        run: gradle clean build
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}

      # Build image
      - name: Create tag
        run: echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: navikt/tpregisteret/tpregisteret
          tags: ${{ env.TAG }}

      # Deploy to dev-fss
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-dev.yaml
          IMAGE: docker.pkg.github.com/navikt/tpregisteret/tpregisteret:${{ env.TAG }}
          TEAM: pensjonsamhandling

#      # Deploy to prod-fss
#      - name: Deploy to prod-fss
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-fss
#          RESOURCE: .nais/nais-prod.yaml
#          IMAGE: docker.pkg.github.com/navikt/tpregisteret/tpregisteret:${{ env.TAG }}
#          TEAM: pensjonsamhandling
